elements = {
    #auth
    "number_field": 'LoginByPhoneView_AccessibilityIds_phoneField',
    "phone_number_next":"LoginByPhoneView_AccessibilityIds_loginAction",
    "phone_pass_cnt":"LoginByPasswordView_AccessibilityIds_passwordField",
    "pass_number_next":"LoginByPasswordView_AccessibilityIds_loginAction",
    "pin_1": 'PincodeView_AccessibilityIds_pinButton1',
    "reset_the_password": "Reset the password",
    "close_eye": "CreatePasswordView_AccessibilityIds_passwordShowHideAction",
    "reset_by_sms": '//XCUIElementTypeButton[@name="SMS"]',
    "reset_by_email": "E-mail",
    "sms_code": '//XCUIElementTypeOther[@name="suggestion"]',
    "enter_code": "LoginByOTPView_AccessibilityIds_codeField",
    "link_agreements": "LoginByPhoneView_AccessibilityIds_agreementAction",
    "user_agreement": "AgreementTermsView_AccessibilityIds_agreementCheckbox",
    "user_terms_collection": "AgreementTermsView_AccessibilityIds_identificationCheckbox",
    "age_qualification": "AgreementTermsView_AccessibilityIds_ageCheckbox",
    "terms_further": "AgreementTermsView_AccessibilityIds_login",
    "user_agreement_offert":"of the service offer",
    "back":"//XCUIElementTypeButton[@name='Back']",
    "user_terms_collection_offer": "for the collection, processing, storage and transfer of personal data",
    "map_of_services":"LoginByPasswordView_AccessibilityIds_opioAction",
    "perm_offices": "Allow Once",
    "icon_map":"ic map",
    "btn_office": '//XCUIElementTypeApplication[@name="Мой О!"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTable/XCUIElementTypeCell[2]/XCUIElementTypeOther[1]/XCUIElementTypeOther',
    "lang": '//XCUIElementTypeButton[@name="LoginByPhoneView_AccessibilityIds_languageAction"]',
    "lang_kg": '//XCUIElementTypeButton[@name="Кыргызча"]',
    "lang_en": '//XCUIElementTypeButton[@name="English"]',
    "lang_ru": '//XCUIElementTypeButton[@name="Русский"]',
    "cancel": 'Cancel',
    "accept_main_alert": '//XCUIElementTypeButton[@name="Allow"]',
    "maps_login": 'LoginByPhoneView_AccessibilityIds_officeMapAction',
    "further": 'Further',
    "password_field": 'CreatePasswordView_AccessibilityIds_passwordField',
    "otp_field": 'LoginByOTPView_AccessibilityIds_codeField',
    "lk_quar": 'ic qr scanner',
    "close_lk_qr": 'ic circle close',
    "plus_balance_lk": '//XCUIElementTypeButton[@name="plus"]',
    "btn_back_from_replenishment": '//XCUIElementTypeNavigationBar[@name="UI.InputOfAmountPayment"]/XCUIElementTypeButton',
    "btn_back_to_lk": '//XCUIElementTypeButton[@name="+996 702 243 852"]',
    "btn_plus_internet": '(//XCUIElementTypeButton[@name="ic plus btn"])[2]',
    "btn_plus_calls": '(//XCUIElementTypeButton[@name="ic plus btn"])[1]',
    "btn_my_numbers": 'My numbers',
    "btn_back_to_my_numbers": '//XCUIElementTypeButton[@name="My numbers"]',
    "btn_saima": 'Saima Telecom',
    "btn_service": 'Service',
    "last_name_lk": '//XCUIElementTypeApplication[@name="Мой О!"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTable/XCUIElementTypeCell[3]/XCUIElementTypeTextField',
    "events": 'Events',
    "back_to_menu": 'Menu',
    "btn_otv": 'O! TV service is not connected',
    "btn_online_support": 'Online support',
    "btn_close_online_support": 'ic circle close',
    "btn_map_menu": 'Map of office and terminals',
    "btn_ostore": 'O!Store',
    "btn_security": 'Security',
    "btn_about_application": 'About application',
    "btn_mektep": 'Mektep, Distance education',
    "share_myo_in_menu": '//XCUIElementTypeNavigationBar[@name="Menu"]/XCUIElementTypeButton',
    "btn_exit": 'Exit',
    "btn_change_lang_menu": 'Change the language',
    "btn_ok_lang_kg_menu": '//XCUIElementTypeButton[@name="Макул"]',
    "btn_ok_lang_ru_menu": '//XCUIElementTypeButton[@name="OK"]',
    "btn_ok_lang_en_menu": '//XCUIElementTypeButton[@name="OK"]',
    "field_email_lk": '//XCUIElementTypeApplication[@name="Мой О!"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTable/XCUIElementTypeCell[1]',



    



    # O!dengi
    "btn_main_Odengi": 'O!Dengi',
    "btn_plus_balance_Odengi": '(//XCUIElementTypeButton[@name="ic plus"])[2]',
    "btn_plus_wallet_Odengi": '(//XCUIElementTypeButton[@name="ic plus"])[1]',
    "btn_bonus": 'О!Bonus',
    "btn_loan": 'Loan',
    "btn_my_cards": 'My cards',
    "btn_history_payments": 'Payment history',
    "btn_bills_and_fines": 'Bills and fines',
    "btn_qr": 'QR and receipt scanner',
    "btn_accept_camera_alert": 'OK',
    "btn_see_all_favorites": '(//XCUIElementTypeStaticText[@name="See all"])[1]',
    "directory_search": '(//XCUIElementTypeStaticText[@name="Directory search"])[1]',
    "phone_number_cnt": "LoginByPasswordView_AccessibilityIds_passwordField",
    "btn_cancel_notif":"//XCUIElementTypeButton[@name='ic circle close']",
    "cnt_qr_notif":'//XCUIElementTypeStaticText[@name="Personal QR code for balance replenishment"]',
    "allow_perm": '//XCUIElementTypeButton[@name="Allow"]',
    "number_7": '//XCUIElementTypeKey[@name="7"]',
    "number_0":'//XCUIElementTypeKey[@name="0"]',
    "number_2":'//XCUIElementTypeKey[@name="2"]',
    "number_4":'//XCUIElementTypeKey[@name="4"]',
    "number_3": '//XCUIElementTypeKey[@name="3"]',
    "number_5": '//XCUIElementTypeKey[@name="5"]',
    "number_6":'//XCUIElementTypeKey[@name="6"]',
    "number_1":'//XCUIElementTypeKey[@name="1"]',
    "number_8":'//XCUIElementTypeKey[@name="8"]',
    "hide_password": '//XCUIElementTypeButton[@name="hidePassword"]',
    "Further1":'//XCUIElementTypeStaticText[@name="Further"]',
    "shift":'//XCUIElementTypeButton[@name="shift"]',
    "Q": '//XCUIElementTypeKey[@name="Q"]',
    "w": '//XCUIElementTypeKey[@name="w"]',
    "e": '//XCUIElementTypeKey[@name="e"]',
    "r": '//XCUIElementTypeKey[@name="r"]',
    "t": '//XCUIElementTypeKey[@name="t"]',
    "y": '//XCUIElementTypeKey[@name="y"]',
    "more": '//XCUIElementTypeKey[@name="more"]',
    "7": '//XCUIElementTypeKey[@name="7"]',
    "6": '//XCUIElementTypeKey[@name="6"]',
    "5": '//XCUIElementTypeKey[@name="5"]',
    "4": '//XCUIElementTypeKey[@name="4"]',
    "3": '//XCUIElementTypeKey[@name="3"]',
    "2": '//XCUIElementTypeKey[@name="2"]',
    "1": '//XCUIElementTypeKey[@name="1"]',
    "Further2": '//XCUIElementTypeButton[@name="Further"]',
    "pin_2": '//XCUIElementTypeStaticText[@name="1"]',
    "cnt_phone":'//XCUIElementTypeApplication[@name="Мой О!"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[1]/XCUIElementTypeTextField',
    "btn_menu":'//XCUIElementTypeButton[@name="Menu"]',
    "btn_personal_profile":'//XCUIElementTypeApplication[@name="Мой О!"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTable/XCUIElementTypeCell[1]',
    "name_lk": '//XCUIElementTypeApplication[@name="Мой О!"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTable/XCUIElementTypeCell[2]',
    "done":'//XCUIElementTypeButton[@name="Done"]',
    "btn_balance_plus":'//XCUIElementTypeButton[@name="plus"]',
    "btn_select_type_payment":'//XCUIElementTypeButton[@name="Select"]',
    "btn_select_ewallet":'E-wallet',
    "btn_continue":'//XCUIElementTypeButton[@name="Continue"]',
    "input_amount":'//XCUIElementTypeApplication[@name="Мой О!"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[1]/XCUIElementTypeOther[3]/XCUIElementTypeOther/XCUIElementTypeTextField',
    "btn_to_pay":'//XCUIElementTypeButton[@name="To pay 5,00 c̲"]',
    "btn_home":'//XCUIElementTypeButton[@name="Home"]',
    "btn_O!dengi":'//XCUIElementTypeButton[@name="O!Dengi"]',
    "my_cards":'//XCUIElementTypeStaticText[@name="My cards"]',
    "my_favorites":'//XCUIElementTypeButton[@name="See all"]',
    "payment_history":'//XCUIElementTypeStaticText[@name="Payment history"]',
    "mobile_operators":'//XCUIElementTypeStaticText[@name="Mobile operators"]',
    "btn_system_ok":'//XCUIElementTypeButton[@name="OK"]',
    "btn_select_mwallet":'(//XCUIElementTypeButton[@name="Select"])[3]',
    "btn_change_payment_type":'//XCUIElementTypeButton[@name="Change"]',
    "wallet_and_banks":'//XCUIElementTypeStaticText[@name="Wallets and banks"]',
    "wallet_Odengi":'//XCUIElementTypeApplication[@name="Мой О!"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTable/XCUIElementTypeCell[1]',
    "hint_number":'//XCUIElementTypeStaticText[@name="996700000167"]',
    "reset_password":'//XCUIElementTypeStaticText[@name="Reset the password"]',









    #LK
    "btn_internet": "internet_leftover",
    "btn_outgoing_call": "outgoing_call_leftover",
    "btn_refill": "ic_refill",
    "btn_lottery": "lottery_view",
    "btn_tariffs": "Tariffs",
    "btn_detalizatation": "Detalization",
    "cnt_searh_bar":"search_src_text",
    "btn_settings_lang":"settingsLang",
    "btn_ru_lang":"lang_ru",
    "btn_ok":"button1",
    "btn_container":"tv_title",
    "btn_calendar": '//XCUIElementTypeNavigationBar[@name="Detalization"]/XCUIElementTypeButton[2]',
    "btn_last_month": 'Last month',
    "btn_abon_spend": '//XCUIElementTypeApplication[@name="Мой О!"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTable/XCUIElementTypeCell[2]',
    "btn_history_detalization": 'History',
    "btn_slider_detalization": '//XCUIElementTypeSwitch[@name="Free events"]',
    "btn_last_week": 'For the last week',
    "btn_choose_period": 'Choose a period',
    "btn_done_bottom_list": '//XCUIElementTypeStaticText[@name="Done"]',
    "btn_history_calendar": '//XCUIElementTypeNavigationBar[@name="History"]/XCUIElementTypeButton[2]',
    "btn_order_details": 'Order details',
    "btn_order_detalization": '(//XCUIElementTypeStaticText[@name="Order details"])[2]',
    "btn_choose_other_format": '//XCUIElementTypeApplication[@name="Мой О!"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeButton',
    "exel_format": 'EXCEL',
    "change_date_in_order_detalization": '//XCUIElementTypeStaticText[@name="From 03.05.2021 to 03.05.2021"]',
    "field_email": '//XCUIElementTypeApplication[@name="Мой О!"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[3]/XCUIElementTypeOther[1]/XCUIElementTypeTextField',
    "field_pin2": '//XCUIElementTypeApplication[@name="Мой О!"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[1]/XCUIElementTypeTextField',
    "confirm_smart_number": '//XCUIElementTypeButton[@name="Confirm"]',
    "click_subnumber": '(//XCUIElementTypeStaticText[@name="+996 702 245 281"])[2]',
    "changing_subnumber": '//XCUIElementTypeNavigationBar[@name="+996 702 245 281"]/XCUIElementTypeButton[2]',
    "delete_from_my_subnumbers": '//XCUIElementTypeStaticText[@name="Delete from my numbers"]',
    "accept_deleting_subnumber": 'OK',
    "click_another_subnumber": '//XCUIElementTypeStaticText[@name="+996 702 242 356"]',
    "field_create_subnumber_name": '//XCUIElementTypeApplication[@name="Мой О!"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeTextField',
    "btn_done": 'Done',
    "btn_subnumber_group": '//XCUIElementTypeApplication[@name="Мой О!"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTable/XCUIElementTypeCell',
    "remove_subnumber_from_group": 'Delete +996 702 242 356',
    "delete_parent_number": '//XCUIElementTypeButton[@name="Delete"]',
    "btn_ok_accept_deleting_number": 'OK',
    "add_the_number": '//XCUIElementTypeButton[@name="Add the number"]',
    "btn_ok_adding_subnumber": 'OK',
    "changing_subnumber_2": '//XCUIElementTypeNavigationBar[@name="Test"]/XCUIElementTypeButton[2]',
    "add_subnumber_little_btn": '//XCUIElementTypeStaticText[@name="Add"]',
    "field_subnumber_phone": '//XCUIElementTypeApplication[@name="Мой О!"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeTextField',
    "btn_less_balance": '//XCUIElementTypeSwitch[@name="Report balance less than 10 soms"]',
    "btn_cancel_subnumber_request": '//XCUIElementTypeStaticText[@name="Cancel request"]',
    "btn_tariffs_subnumber": 'Tariff change',
    "btn_basic_tariffs_subnumber": '//XCUIElementTypeApplication[@name="Мой О!"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTable/XCUIElementTypeCell[5]',
    "btn_onoi_for_subnumber": '//XCUIElementTypeApplication[@name="Мой О!"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTable/XCUIElementTypeCell[4]',
    "btn_change_tariffs_subnumber": '//XCUIElementTypeButton[@name="Change the tariff"]',
    "btn_connected_services": 'Connected services',
    "btn_affordable_services_sport": '//XCUIElementTypeApplication[@name="Мой О!"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTable/XCUIElementTypeCell[2]',
    "btn_connect_service_sport": '//XCUIElementTypeStaticText[@name="Connect"]',
    "btn_yes": 'Yes',
    "btn_service_sport_detail": '//XCUIElementTypeApplication[@name="Мой О!"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTable/XCUIElementTypeCell[1]',
    "btn_turn_of_service": '//XCUIElementTypeButton[@name="Turn off service"]',
    "btn_active_services_subnumber": '//XCUIElementTypeApplication[@name="Мой О!"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTable/XCUIElementTypeCell[1]',
    "btn_close_changing_name": 'Close',
    "btn_close_invalid_pin": 'Close',
    "btn_delete_keyboard": 'delete',
    "change_subnumber_name": '//XCUIElementTypeApplication[@name="Мой О!"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther',


    #Dengi
    "btn_o!dengi":"menu_wallet",
    "btn_self_refill":"ic_refill",
    "btn_choose_payment_type":"choose",
    "cnt_amount":"amount",
    "btn_pay":"pay_btn",
}

elements_path = {
    #auth
    #LK
    "btn_cancel_notif": "//XCUIElementTypeButton[@name='ic circle close']",
    #Dengi
    "btn_ewallet":"//androidx.recyclerview.widget.RecyclerView[@index='1']/android.view.ViewGroup[@index='0']",
    "btn_mwallet": "//androidx.recyclerview.widget.RecyclerView[@index='1']/android.view.ViewGroup[@index='1']",
    "btn_bcard": "//androidx.recyclerview.widget.RecyclerView[@index='1']/android.view.ViewGroup[@index='2']",
    "btn_side_menu":"//androidx.drawerlayout.widget.DrawerLayout[@index='0']/android.view.ViewGroup[@index='0']/android.widget.LinearLayout[@index='0']/android.widget.LinearLayout[@index='0']/android.view.ViewGroup[@index='0']/android.widget.ImageButton[@index='0']",
    "btn_setings":"//androidx.recyclerview.widget.RecyclerView[@index='0']/androidx.appcompat.widget.LinearLayoutCompat[@index='5']",

}

# elements_lk = {
#     "btn_internet":"internet_leftover",
#     "btn_outgoing_call":"outgoing_call_leftover",
#     "btn_refill":"ic_refill",
#     "btn_sub_numbers":"sub_numbers",
#     "btn_lottery":"lottery_view",
#     "btn_detalizatation":"detalizatation",
# }

list_activity = {
    "LoginByPasswordActivity":".ui.auth.login.password.LoginByPasswordActivity",
    "UseConditionConfirmActivity":".ui.auth.conditions_confirm.UseConditionConfirmActivity",
    "PhoneNumberExistenceCheckActivity":".ui.auth.existence_check.PhoneNumberExistenceCheckActivity",
    "InternetServiceActivity": ".ui.services.group.internet.InternetServiceActivity",
    "CallServiceActivity": ".ui.services.group.call.CallServiceActivity",
    "ManageNumbersActivity": ".ui.manage_numbers.ManageNumbersActivity",
    "LotteryInfoActivity": ".ui.lottery.info.LotteryInfoActivity",
    "ServiceCategoryActivity": ".ui.services.service.category.ServiceCategoryActivity",
    "TariffCategoryActivity": ".ui.services.tariff.category.TariffCategoryActivity",
    "CompleteDetalizationActivity":".ui.detalization.replenish_detalization.CompleteDetalizationActivity",
    #Dengi
    "GettingWalletStatusActivity":"wallet.ui.account.getting_wallet_status.GettingWalletStatusActivity",
    "ServicePaymentActivity":"wallet.ui.payment.service.ServicePaymentActivity",
    "ChoosePaymentTypeActivity":"wallet.ui.payment.type.ChoosePaymentTypeActivity",
    "ReplenishmentConfirmationActivity":"wallet.ui.replenish.confirmation.ReplenishmentConfirmationActivity",
}
